### ISSUE TITLE
Black border around edges

### ISSUE THREAD

**Issue by bjornsallarp** [gdawg/uiimage-dsp#4]
When applying any effect it also adds a black border around the edges of the image. For example, it seems the more gaussian blur is added the wider the black border becomes. I hope you get the time to look at this and thanks for the great work!

**Comment by gdawg** [comment]
Hi there Bjorn,

I think this is a natural artifact based on the fact that the edge pixels have their color average calculated using zero because there's no pixels further off the edge to blur with. 

In apps where I've used the library I crop by a few pixels after applying a blur to remove this but there may be a better option. Any thoughts on what the norm would be?

**Comment by gdawg** [comment]
closing this as expected.
